/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.ImageIcon;

/**
 *
 * @author konaf
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/descarga.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opMoneda = new javax.swing.JMenuItem();
        opTemperatura = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        opSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alura.png"))); // NOI18N
        escritorio.add(jLabel1);
        jLabel1.setBounds(0, -40, 400, 400);

        jMenu1.setText("Menu..");

        opMoneda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cambio-de-divisas.png"))); // NOI18N
        opMoneda.setText("Conversor Moneda");
        opMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMonedaActionPerformed(evt);
            }
        });
        jMenu1.add(opMoneda);

        opTemperatura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/termometro.png"))); // NOI18N
        opTemperatura.setText("Conversor Temperatura");
        jMenu1.add(opTemperatura);
        jMenu1.add(jSeparator2);

        opSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        opSalir.setText("Salir");
        jMenu1.add(opSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opMonedaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JMenuItem opMoneda;
    public javax.swing.JMenuItem opSalir;
    public javax.swing.JMenuItem opTemperatura;
    // End of variables declaration//GEN-END:variables

}
